### ISSUE TITLE
[Bug] debug mode not working on 1980's

### ISSUE THREAD

**Issue by NightlyCanary** [BTELNYY/yansimsavegameeditor#1]
Don't know if I can put this here but, whenever I try to use the latest release, the debug commands never show up in 1980s mode. I can try to enable it over and over but, it still doesn't show up.

**Comment by BTELNYY** [comment]
Yes, replying here is a good idea. 
If you can, make sure you selected the correct save file, you are not running the app as a admin, and the game has run on that system.

Note: save files from 1-3 are for 202X and 11-13 are for 1980's mode.

You will need to reset your day for the changes to take effect. 

Are there any errors in red when executing the commands?

**Comment by BTELNYY** [comment]
I have tested and debug mode still works. I am closing this issue as it has been patched.

**Comment by BTELNYY** [comment]
I have tested and seen that there are no issues, make sure your on the newest build of both the game and my tool and make sure to restart your day. Also, if you have some kind of red text, post it as a new issue.
