### ISSUE TITLE
Game Config couldnt load

### ISSUE THREAD

**Issue by Legend-Recalls** [BTELNYY/yansimsavegameeditor#11]
![image](https://user-images.githubusercontent.com/69719681/177042358-d13227c2-a8e2-4368-ba51-433501f308db.png)
happens when  i try to load save file from 1980s mode

**Comment by BTELNYY** [comment]
Could you also provide your latest logs? (In the logs folder)

**Comment by Legend-Recalls** [comment]
[03-07-2022.log](https://github.com/BTELNYY/yansimsavegameeditor/files/9035118/03-07-2022.log)

**Comment by BTELNYY** [comment]
Ah, an issue with the clubs. What club are you in within the save which failed loading?

**Comment by Legend-Recalls** [comment]
newspaper club

**Comment by BTELNYY** [comment]
oh yeah, I should probs add that....

**Comment by Legend-Recalls** [comment]
:)

**Comment by BTELNYY** [comment]
Please test by downloading the updated version: https://github.com/BTELNYY/yansimsavegameeditor/releases/latest

**Comment by BTELNYY** [comment]
If there is an issue, re-open this issue.
